"""Terminal entry point and service: generate real voiceover audio for one
persisted Production's scenes, from each scene's own EXACT narration text -
never an LLM rewrite.

    python -m research.voice --production-id PRODUCTION_ID [--scene N] [--voice NAME] [--language CODE]

    load production -> for each requested scene not already narrated: take
    scene["voiceover"] EXACTLY as Production wrote it -> call the voice
    provider -> upload the result to storage -> validate -> persist
    (success or failure, one row per attempt) -> report

Audio is its own media layer, not a Media Generation afterthought:

    Visuals + scene/ambient audio + voiceover + music + sound effects
        -> audio mixing -> final video

This chapter (V1) builds ONLY voiceover generation - one scene's narration
in, one audio clip out. Music/SFX generation and the eventual audio-mixing
stage that combines all these layers are separate, later chapters; this
module does not attempt either.

Voice Generation is structurally parallel to (not part of) Media Generation
(`research.media`, which handles image/video): it has its own provider
abstraction (`research.media_providers.VoiceProvider`) but reuses the SAME
persistence architecture (`research.media_store.MediaRepository`,
`media_runs`/`media_assets`) and the SAME idempotency/partial-success
philosophy as image/video generation (see `research.media_store`'s module
docstring) - a transient failure on one scene's narration does not discard
scenes that already succeeded.

Deliberately, this module does NOT build a prompt and does NOT consult
Media Direction (`research.media_direction`): a scene's own `voiceover` text
is passed to the provider completely unchanged. Media Direction is HOW a
human wants the VISUALS represented; it has no narration-changing role, and
none is added here. Rewriting or adapting narration via an LLM is a
distinct, NOT-YET-BUILT future capability, never conflated with this
module, which only ever executes Production's own approved words:

    Production -> exact approved script -> voice generation      (this module)
    Production -> LLM rewrites script -> voice generation         (NOT built)

Veo's source scene clips (see `research.veo`) already contain generated
scene/ambient audio of their own; Assembly V1 (`research.ffmpeg_engine`)
deliberately dropped it when concatenating, producing a mute final video -
intentional, not a bug (see that module's own docstring). This module is
about deliberate VOICEOVER, a separate audio layer; it has no opinion on
and does not touch that source scene audio. A future Assembly/audio-mixing
chapter can choose to preserve, mute, mix with, or replace it - nothing
about that choice is made here, and the six existing Veo scene videos are
never read, modified, or regenerated by this module.

Needs SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY and GEMINI_API_KEY
(MEDIA_VOICE_PROVIDER/MEDIA_VOICE_MODEL optional, only "gemini" implemented).
Exit codes: 0 at least one requested scene is now narrated (whether
generated now or already done), 1 the production/its scenes cannot be used
(missing production, unknown scene, or a scene with no narration to read),
2 bad arguments / missing configuration, 3 every requested scene failed and
none were already completed.
"""

from __future__ import annotations

import argparse
import sys
from collections.abc import Callable, Sequence
from dataclasses import dataclass, field

from research.config import Settings
from research.logging import configure_logging, get_logger
from research.media_providers import MediaProviderConfigError, MediaProviderError, VoiceProvider
from research.media_schema import AssetStatus, AssetType, AudioSubtype, GeneratedAsset
from research.media_storage import StorageError, SupabaseStorage, extension_for_mime_type, scene_asset_path
from research.media_store import MediaRepository, build_run_payload, compute_run_key
from research.media_validation import validate_asset
from research.persistence import PersistenceConfigError, SupabaseDatabase

log = get_logger("research.voice")

Progress = Callable[[str], None]

EXIT_OK, EXIT_SOURCE, EXIT_CONFIG, EXIT_FAILED = 0, 1, 2, 3

VOICE_PACK_VERSION = "voice-v1"

# The one provider implemented in V1. MEDIA_VOICE_PROVIDER is read so a
# future second provider needs no CLI change, but any other value is refused.
VOICE_PROVIDER_NAME = "gemini"


class VoiceSourceError(Exception):
    """The requested production cannot be used as it currently stands. Nothing was changed."""


class VoiceConfigError(Exception):
    """Voice generation is not configured usably (e.g. an unimplemented provider)."""


@dataclass(frozen=True)
class VoiceRunOutcome:
    status: str  # "completed" | "partial" | "failed"
    run_id: str
    run_key: str
    requested_scenes: tuple[int, ...]
    completed_scenes: tuple[int, ...] = ()
    already_completed_scenes: tuple[int, ...] = ()
    failed_scenes: dict[int, str] = field(default_factory=dict)


def _ignore(_: str) -> None:
    pass


def run_voice_generation(
    production_id: str,
    *,
    repository: MediaRepository,
    storage: SupabaseStorage,
    voice_provider: VoiceProvider,
    voice: str = "Kore",
    language: str = "en-US",
    scenes: Sequence[int] | None = None,
    progress: Progress = _ignore,
) -> VoiceRunOutcome:
    """Generate voiceover audio for `production_id`'s scenes (all of them,
    or only `scenes` if given), from each scene's own `voiceover` text -
    passed to the provider EXACTLY as Production wrote it, never rewritten.

    Raises `VoiceSourceError` if the production cannot be resolved, if a
    requested scene does not exist, or if a requested scene has no
    narration text at all; otherwise never raises for a single scene's
    generation failure (mirrors `research.media`'s own per-scene handling -
    see that module's docstring). Unlike `research.media`, this never loads
    a product profile: narration is read verbatim from the scene, with no
    capability descriptions or out-of-scope list to weave into a prompt -
    there is no prompt at all."""
    production = repository.get_production(production_id)
    if production is None:
        raise VoiceSourceError(f"Production {production_id} does not exist")

    all_scenes = production.row.get("scenes") or []
    by_number = {s["number"]: s for s in all_scenes}
    requested = tuple(scenes) if scenes else tuple(sorted(by_number))
    unknown = [n for n in requested if n not in by_number]
    if unknown:
        raise VoiceSourceError(
            f"scene(s) {unknown} do not exist in production {production_id} (has scenes {sorted(by_number)})"
        )
    no_narration = [n for n in requested if not (by_number[n].get("voiceover") or "").strip()]
    if no_narration:
        raise VoiceSourceError(f"scene(s) {no_narration} have no voiceover text to narrate")
    progress(f"✓ Production loaded: {len(requested)} scene(s) requested, each read from its own approved narration")

    # A run's identity reflects only the voice provider/model (and nothing
    # from image/video generation - the `image_*`/`video_*` args are always
    # None here, matching research.media's own "never leak another
    # modality's configuration" rule). Media Direction never applies to
    # voice (see the module docstring), so it is never folded in here.
    run_key = compute_run_key(
        production_id=production_id, image_provider=None, image_model=None, video_provider=None,
        video_model=None, voice_provider=VOICE_PROVIDER_NAME, voice_model=voice_provider.model,
        pack_version=VOICE_PACK_VERSION,
    )
    existing_run_id = repository.find_run(run_key)
    if existing_run_id is not None:
        run_id = existing_run_id
    else:
        saved = repository.save_run(
            build_run_payload(
                production_id=production_id, image_provider=None, image_model=None, video_provider=None,
                video_model=None, voice_provider=VOICE_PROVIDER_NAME, voice_model=voice_provider.model,
                run_key=run_key, scene_count=len(all_scenes),
                manifest={
                    "pack_version": VOICE_PACK_VERSION, "production_id": production_id,
                    "voice": voice, "language": language,
                },
                pack_version=VOICE_PACK_VERSION,
            )
        )
        run_id = saved.run_id
    progress(f"✓ Voice run {'found' if existing_run_id else 'created'}: {run_id}")

    completed: list[int] = []
    already_completed: list[int] = []
    failed: dict[int, str] = {}
    for number in requested:
        if repository.find_completed_asset(run_id, number):
            progress(f"✓ Scene {number} already narrated; skipping")
            already_completed.append(number)
            continue

        narration = by_number[number]["voiceover"]  # Production's own exact words - never rewritten here
        cost_amount: float | None = None
        cost_currency: str | None = None
        try:
            audio = voice_provider.generate_voice(narration, voice=voice, language=language)
            cost_amount, cost_currency = audio.cost_amount, audio.cost_currency
            extension = extension_for_mime_type(audio.mime_type)
            path = scene_asset_path(
                production_id=production_id, media_run_id=run_id, scene_number=number, extension=extension
            )
            stored = storage.upload(path, audio.data, content_type=audio.mime_type)
            asset = GeneratedAsset(
                scene_number=number, asset_type=AssetType.AUDIO, audio_subtype=AudioSubtype.VOICEOVER,
                status=AssetStatus.COMPLETED, provider=VOICE_PROVIDER_NAME, model=voice_provider.model,
                prompt=narration, generation_config={"voice": voice, "language": language},
                product_capability_refs=(), provider_metadata=dict(audio.metadata),
                storage_bucket=stored.bucket, storage_path=stored.path, storage_url=stored.public_url,
                mime_type=audio.mime_type, duration_seconds=audio.duration_seconds,
                cost_amount=cost_amount, cost_currency=cost_currency,
            )
            validate_asset(asset, production=production.row)
            repository.save_asset(media_run_id=run_id, production_id=production_id, asset=asset)
            completed.append(number)
            progress(f"✓ Scene {number} voiceover generated: {stored.public_url}")
        except (MediaProviderError, StorageError) as exc:
            asset = GeneratedAsset(
                scene_number=number, asset_type=AssetType.AUDIO, audio_subtype=AudioSubtype.VOICEOVER,
                status=AssetStatus.FAILED, provider=VOICE_PROVIDER_NAME, model=voice_provider.model,
                prompt=narration, generation_config={"voice": voice, "language": language},
                product_capability_refs=(), cost_amount=cost_amount, cost_currency=cost_currency,
                error_message=f"{type(exc).__name__}: {exc}",
            )
            validate_asset(asset, production=production.row)
            repository.save_asset(media_run_id=run_id, production_id=production_id, asset=asset)
            failed[number] = str(exc)
            progress(f"✗ Scene {number} failed: {exc}")

    total_ok = len(completed) + len(already_completed)
    status = "completed" if total_ok == len(requested) else ("partial" if total_ok > 0 else "failed")
    return VoiceRunOutcome(
        status=status, run_id=run_id, run_key=run_key, requested_scenes=requested,
        completed_scenes=tuple(completed), already_completed_scenes=tuple(already_completed), failed_scenes=failed,
    )


def _resolve_voice_provider(settings: Settings) -> VoiceProvider:
    provider_name = (settings.media_voice_provider or VOICE_PROVIDER_NAME).strip().lower()
    if provider_name != VOICE_PROVIDER_NAME:
        raise VoiceConfigError(f"MEDIA_VOICE_PROVIDER={provider_name!r} is not implemented; only 'gemini' is")
    from research.gemini_tts import GeminiVoiceProvider

    return GeminiVoiceProvider.from_settings(settings)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m research.voice",
        description="Generate voiceover audio for one production's scenes, from each scene's own exact narration.",
    )
    parser.add_argument("--production-id", required=True, help="id of a stored `productions` row")
    parser.add_argument(
        "--scene", type=int, action="append", dest="scenes",
        help="generate only this scene number (repeatable); default: every scene",
    )
    parser.add_argument("--voice", default="Kore", help="Gemini prebuilt voice name (default: Kore)")
    parser.add_argument("--language", default="en-US", help="BCP-47 language code (default: en-US)")
    args = parser.parse_args(argv)

    settings = Settings.from_env()
    configure_logging(settings.log_level)
    if not (settings.supabase_url and settings.supabase_service_role_key):
        print("error: SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY must be set", file=sys.stderr)
        return EXIT_CONFIG
    try:
        voice_provider = _resolve_voice_provider(settings)
    except (VoiceConfigError, MediaProviderConfigError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return EXIT_CONFIG
    try:
        repository = MediaRepository(
            SupabaseDatabase(settings.supabase_url, settings.supabase_service_role_key)
        )
        storage = SupabaseStorage(
            settings.supabase_url, settings.supabase_service_role_key,
            bucket=settings.media_storage_bucket or "media-assets",
        )
    except PersistenceConfigError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return EXIT_CONFIG

    print("Voice Generation\n────────────────────────────────", flush=True)
    try:
        outcome = run_voice_generation(
            args.production_id, repository=repository, storage=storage, voice_provider=voice_provider,
            voice=args.voice, language=args.language, scenes=args.scenes,
            progress=lambda line: print(line, flush=True),
        )
    except VoiceSourceError as exc:
        print(f"\nCannot generate voice: {exc}", file=sys.stderr)
        return EXIT_SOURCE
    except Exception as exc:
        print(f"\nVoice generation failed: {type(exc).__name__}: {exc}", file=sys.stderr)
        return EXIT_FAILED

    total_new = len(outcome.completed_scenes)
    total_ok = total_new + len(outcome.already_completed_scenes)
    print(
        f"\nVoice run {outcome.status}: {outcome.run_id} "
        f"({total_ok}/{len(outcome.requested_scenes)} scene(s) complete, {total_new} generated now, "
        f"{len(outcome.failed_scenes)} failed)."
    )
    if outcome.failed_scenes:
        for number, message in outcome.failed_scenes.items():
            print(f"  scene {number}: {message}", file=sys.stderr)
    return EXIT_FAILED if total_ok == 0 else EXIT_OK


if __name__ == "__main__":
    sys.exit(main())
